variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
- master

pool:
  name: Demo
  demands:
   - agent.name -equals demo

steps:
  - task: Bash@3
    displayName: 'Use JDK11 by default'
    inputs:
      targetType: 'inline'
      script: |
        echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME_11_X64"
      
  - task: Cache@2
    displayName: 'Cache Maven local repo'
    inputs:
      key: '"funcs" | maven | "$(Agent.OS)" | pom.xml'
      restoreKeys: |
      path: $(MAVEN_CACHE_FOLDER)

  - task: Maven@3
    displayName: 'Build and Test'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: package
      mavenVersionSelection: Path
      jdkSourceOption: 'PreInstalled'
      mavenPath: /usr/share/maven
      mavenOptions: '-Xmx2048m'
      mavenVersionOption: 'Default'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11.0.11'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
